#http://localhost:8081/swagger-ui.html

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=quindioflix
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

server.port=8081